-- ============================================================
-- TodoTech Shop — Script de base de datos Oracle
-- Ejecutar en orden
-- ============================================================

-- Tabla CLIENTES (MOD-08 — CRUD)
CREATE TABLE CLIENTES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFICACION  VARCHAR2(20)  NOT NULL UNIQUE, -- RN-01
    NOMBRE          VARCHAR2(100) NOT NULL,
    TELEFONO        VARCHAR2(20)  NOT NULL,
    CORREO          VARCHAR2(100) NOT NULL,
    ACTIVO          NUMBER(1)     DEFAULT 1 NOT NULL
);

-- Tabla PRODUCTOS (MOD-02)
CREATE TABLE PRODUCTOS (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO              VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE              VARCHAR2(100) NOT NULL,
    DESCRIPCION         VARCHAR2(300),
    PRECIO              NUMBER(12,2)  NOT NULL,
    STOCK_DISPONIBLE    NUMBER(10)    DEFAULT 0 NOT NULL,
    UBICACION_BODEGA    VARCHAR2(50),
    ACTIVO              NUMBER(1)     DEFAULT 1 NOT NULL
);

-- Tabla ORDENES (MOD-01)
CREATE TABLE ORDENES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_ORDEN    VARCHAR2(20)  NOT NULL UNIQUE, -- RN-16
    ID_CLIENTE      NUMBER        NOT NULL,
    CLAVE_SECRETA   VARCHAR2(10)  NOT NULL,
    TOTAL           NUMBER(12,2)  DEFAULT 0,
    ESTADO          VARCHAR2(20)  DEFAULT 'CREADA' NOT NULL,
    MEDIO_PAGO      VARCHAR2(30),
    FECHA_CREACION  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDEN_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);

-- Tabla DETALLE_ORDEN (MOD-01)
CREATE TABLE DETALLE_ORDEN (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ORDEN        NUMBER        NOT NULL,
    ID_PRODUCTO     NUMBER        NOT NULL,
    CANTIDAD        NUMBER(10)    NOT NULL,
    PRECIO_UNITARIO NUMBER(12,2)  NOT NULL,
    CONSTRAINT FK_DETALLE_ORDEN    FOREIGN KEY (ID_ORDEN)    REFERENCES ORDENES(ID),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);

-- Tabla MOVIMIENTOS_INVENTARIO (MOD-07)
CREATE TABLE MOVIMIENTOS_INVENTARIO (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRODUCTO     NUMBER        NOT NULL,
    TIPO            VARCHAR2(20)  NOT NULL, -- ENTRADA, SALIDA, AJUSTE
    CANTIDAD        NUMBER(10)    NOT NULL,
    MOTIVO          VARCHAR2(200),
    USUARIO         VARCHAR2(50)  NOT NULL,
    FECHA           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MOV_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);

-- Tabla USUARIOS (MOD-06)
CREATE TABLE USUARIOS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100) NOT NULL,
    USUARIO     VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD    VARCHAR2(100) NOT NULL,
    ROL         VARCHAR2(20)  NOT NULL, -- VENDEDOR, CAJERO, DESPACHADOR, ADMINISTRADOR
    ACTIVO      NUMBER(1)     DEFAULT 1 NOT NULL
);

-- Tabla DEVOLUCIONES (MOD-09)
CREATE TABLE DEVOLUCIONES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ORDEN    NUMBER        NOT NULL,
    MOTIVO      VARCHAR2(300) NOT NULL,
    ESTADO      VARCHAR2(20)  DEFAULT 'PENDIENTE' NOT NULL, -- PENDIENTE, APROBADA, RECHAZADA
    FECHA       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DEV_ORDEN FOREIGN KEY (ID_ORDEN) REFERENCES ORDENES(ID)
);

CREATE TABLE PROVEEDORES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100) NOT NULL,
    NIT         VARCHAR2(20)  NOT NULL UNIQUE,
    TELEFONO    VARCHAR2(20)  NOT NULL,
    CORREO      VARCHAR2(100) NOT NULL,
    ACTIVO      NUMBER(1)     DEFAULT 1 NOT NULL
);

CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_PRODUCTO  NUMBER NOT NULL,
    ID_PROVEEDOR NUMBER NOT NULL,
    CONSTRAINT PK_PROD_PROV PRIMARY KEY (ID_PRODUCTO, ID_PROVEEDOR),
    CONSTRAINT FK_PP_PRODUCTO  FOREIGN KEY (ID_PRODUCTO)  REFERENCES PRODUCTOS(ID),
    CONSTRAINT FK_PP_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID)
);

-- Sequence para número de orden (RN-16: único y secuencial)
CREATE SEQUENCE SEQ_NUMERO_ORDEN
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- Datos de prueba mínimos
INSERT INTO USUARIOS (NOMBRE, USUARIO, PASSWORD, ROL)
VALUES ('Administrador', 'admin', 'admin123', 'ADMINISTRADOR');

INSERT INTO USUARIOS (NOMBRE, USUARIO, PASSWORD, ROL)
VALUES ('Vendedor Demo', 'vendedor', 'vend123', 'VENDEDOR');

INSERT INTO USUARIOS (NOMBRE, USUARIO, PASSWORD, ROL)
VALUES ('Cajero Demo', 'cajero', 'caj123', 'CAJERO');

COMMIT;
