-- ============================================================
-- TodoTech Shop — Script completo Oracle
-- ============================================================

-- ── PASO 1: Ejecutar como SYSDBA ────────────────────────────
ALTER SESSION SET CONTAINER = XEPDB1;

CREATE USER todotech IDENTIFIED BY todotech123;
GRANT CONNECT, RESOURCE TO todotech;
GRANT UNLIMITED TABLESPACE TO todotech;

-- ── PASO 2: Conectarse como usuario todotech ───────────────

-- ================= CLIENTES =================
CREATE TABLE CLIENTES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    IDENTIFICACION  VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE          VARCHAR2(100) NOT NULL,
    TELEFONO        VARCHAR2(20)  NOT NULL,
    CORREO          VARCHAR2(100) NOT NULL,
    ACTIVO          NUMBER(1)     DEFAULT 1 NOT NULL
);

-- ================= USUARIOS =================
CREATE TABLE USUARIOS (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE      VARCHAR2(100) NOT NULL,
    USUARIO     VARCHAR2(50)  NOT NULL UNIQUE,
    PASSWORD    VARCHAR2(100) NOT NULL,
    ROL         VARCHAR2(20)  NOT NULL,
    ACTIVO      NUMBER(1)     DEFAULT 1 NOT NULL
);

-- ================= PRODUCTOS =================
CREATE TABLE PRODUCTOS (
    ID                  NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CODIGO              VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE              VARCHAR2(100) NOT NULL,
    DESCRIPCION         VARCHAR2(300),
    PRECIO              NUMBER(12,2)  NOT NULL,
    STOCK_DISPONIBLE    NUMBER(10)    DEFAULT 0 NOT NULL,
    UBICACION_BODEGA    VARCHAR2(50),
    ACTIVO              NUMBER(1)     DEFAULT 1 NOT NULL
);

-- ================= PROVEEDORES =================
CREATE TABLE PROVEEDORES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NIT         VARCHAR2(20)  NOT NULL UNIQUE,
    NOMBRE      VARCHAR2(100) NOT NULL,
    TELEFONO    VARCHAR2(20)  NOT NULL,
    CORREO      VARCHAR2(100) NOT NULL,
    ACTIVO      NUMBER(1)     DEFAULT 1 NOT NULL
);

-- Relación muchos a muchos PRODUCTO - PROVEEDOR
CREATE TABLE PRODUCTO_PROVEEDOR (
    ID_PRODUCTO  NUMBER NOT NULL,
    ID_PROVEEDOR NUMBER NOT NULL,
    CONSTRAINT PK_PROD_PROV PRIMARY KEY (ID_PRODUCTO, ID_PROVEEDOR),
    CONSTRAINT FK_PP_PRODUCTO  FOREIGN KEY (ID_PRODUCTO)  REFERENCES PRODUCTOS(ID),
    CONSTRAINT FK_PP_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDORES(ID)
);

-- ================= ORDENES =================
CREATE TABLE ORDENES (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NUMERO_ORDEN    VARCHAR2(20)  NOT NULL UNIQUE,
    ID_CLIENTE      NUMBER        NOT NULL,
    CLAVE_SECRETA   VARCHAR2(10)  NOT NULL,
    TOTAL           NUMBER(12,2)  DEFAULT 0,
    ESTADO          VARCHAR2(20)  DEFAULT 'CREADA' NOT NULL,
    MEDIO_PAGO      VARCHAR2(30),
    FECHA_CREACION  TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_ORDEN_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID)
);

-- ================= DETALLE ORDEN =================
CREATE TABLE DETALLE_ORDEN (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ORDEN        NUMBER        NOT NULL,
    ID_PRODUCTO     NUMBER        NOT NULL,
    CANTIDAD        NUMBER(10)    NOT NULL,
    PRECIO_UNITARIO NUMBER(12,2)  NOT NULL,
    CONSTRAINT FK_DETALLE_ORDEN    FOREIGN KEY (ID_ORDEN)    REFERENCES ORDENES(ID),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);

-- ================= INVENTARIO =================
CREATE TABLE MOVIMIENTOS_INVENTARIO (
    ID              NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_PRODUCTO     NUMBER        NOT NULL,
    TIPO            VARCHAR2(20)  NOT NULL,
    CANTIDAD        NUMBER(10)    NOT NULL,
    MOTIVO          VARCHAR2(200),
    USUARIO         VARCHAR2(50)  NOT NULL,
    FECHA           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_MOV_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTOS(ID)
);

-- ================= DEVOLUCIONES =================
CREATE TABLE DEVOLUCIONES (
    ID          NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ID_ORDEN    NUMBER        NOT NULL,
    MOTIVO      VARCHAR2(300) NOT NULL,
    ESTADO      VARCHAR2(20)  DEFAULT 'PENDIENTE' NOT NULL,
    FECHA       TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
    CONSTRAINT FK_DEV_ORDEN FOREIGN KEY (ID_ORDEN) REFERENCES ORDENES(ID)
);

-- ================= SECUENCIA =================
CREATE SEQUENCE SEQ_NUMERO_ORDEN
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

-- ── PASO 3: DATOS DE PRUEBA ────────────────────────────────

INSERT INTO USUARIOS (NOMBRE, USUARIO, PASSWORD, ROL)
VALUES ('Administrador', 'admin', 'admin123', 'ADMINISTRADOR');

INSERT INTO USUARIOS (NOMBRE, USUARIO, PASSWORD, ROL)
VALUES ('Vendedor Demo', 'vendedor', 'vend123', 'VENDEDOR');

INSERT INTO USUARIOS (NOMBRE, USUARIO, PASSWORD, ROL)
VALUES ('Cajero Demo', 'cajero', 'caj123', 'CAJERO');

INSERT INTO USUARIOS (NOMBRE, USUARIO, PASSWORD, ROL)
VALUES ('Despachador Demo', 'despacho', 'desp123', 'DESPACHADOR');

INSERT INTO CLIENTES (IDENTIFICACION, NOMBRE, TELEFONO, CORREO)
VALUES ('1001234567', 'Juan Pérez', '3001234567', 'juan@email.com');

INSERT INTO CLIENTES (IDENTIFICACION, NOMBRE, TELEFONO, CORREO)
VALUES ('1009876543', 'María López', '3109876543', 'maria@email.com');

INSERT INTO CLIENTES (IDENTIFICACION, NOMBRE, TELEFONO, CORREO)
VALUES ('1005551234', 'Carlos Ruiz', '3205551234', 'carlos@email.com');

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK_DISPONIBLE, UBICACION_BODEGA)
VALUES ('PROD-001', 'Laptop Dell Inspiron 15', 'Intel Core i5, 8GB RAM, 256GB SSD', 2500000, 10, 'A-01');

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK_DISPONIBLE, UBICACION_BODEGA)
VALUES ('PROD-002', 'Mouse Inalámbrico Logitech', 'Mouse ergonómico 2.4GHz', 85000, 50, 'B-03');

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK_DISPONIBLE, UBICACION_BODEGA)
VALUES ('PROD-003', 'Teclado Mecánico Redragon', 'Switch Blue, RGB, USB', 180000, 25, 'B-04');

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK_DISPONIBLE, UBICACION_BODEGA)
VALUES ('PROD-004', 'Monitor Samsung 24"', 'Full HD 1080p, 75Hz, HDMI', 650000, 8, 'C-02');

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK_DISPONIBLE, UBICACION_BODEGA)
VALUES ('PROD-005', 'Auriculares Sony WH-1000XM4', 'Cancelación de ruido activa, Bluetooth', 950000, 15, 'D-01');

INSERT INTO PRODUCTOS (CODIGO, NOMBRE, DESCRIPCION, PRECIO, STOCK_DISPONIBLE, UBICACION_BODEGA)
VALUES ('PROD-006', 'Disco Duro Externo Seagate 1TB', 'USB 3.0, portátil', 220000, 30, 'B-05');

COMMIT;

-- Verificación final
SELECT TABLE_NAME FROM USER_TABLES ORDER BY TABLE_NAME;